# Generated by Django 5.0.2 on 2024-03-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cvv',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name_on_card',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
