# Generated by Django 5.0.2 on 2024-03-31 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name_on_card',
            field=models.CharField(default='Visa', max_length=100),
        ),
    ]
