# Generated by Django 5.0.2 on 2024-04-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_alter_payment_expiry_date_alter_payment_name_on_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
